### ISSUE TITLE
Práctica de Hilos con Windows Form

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-final-de-hilos-equipohjf#2]
El estudiante integra una práctica 7 para implementar hilos en una aplicación de escritorio utilizando C# en Visual Studio.

La practica se debe desarrollar en Windows Form para implementar hilos con una aplicación de escritorio de Visual Studio

La aplicación debe aplicar la multitarea para realizar diferentes tareas a la vez.

**Comment by FedericoVictorianoSierra** [comment]
[Practica 7 (Federico Victoriano Sierra (4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipohjf/files/8438834/Practica.7.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 7 (José Antonio Balbuena Cruz (4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipohjf/files/8438843/Practica.7.Jose.Antonio.Balbuena.Cruz.4US.pdf)

**Comment by Heidi-19** [comment]
[Practica 7 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipohjf/files/8438886/Practica.7.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
